title: Shawn Anastasio
description: >
    A little blog showcasing some of my projects and findings over the years.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anastas.io" # the base hostname & protocol for your site
twitter_username: shawnanastasio
github_username:  shawnanastasio

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
